# Header
menu:
  主页: 
  学无止境: /categories/conding
  碎言碎语: /categories/life
  关于我: /about


rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tagcloud
- archive
- links


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: YYYY年MM月
show_count: true

auto_excerpt:
  enable: true
  length: 300

highlight_style:
  on: true
  inline_code: 8  # Value: 0 - 9 可选，3还不错
  code_block: 1  # Value: 0 - 4 

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
  
addthis:
  enable: true   
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true


disqus_shortname: jody

#### Analytics  
cnzz: true 
baidu_tongji: true

# 友情链接
links:
- name: baizn
  link: http://baizn.github.io
- name: ClassRun
  link: http://init.funlee.cn
- name: tangqk
  link: https://wxxtqk.github.io
- name: zy380196088
link: http://zy380196088.github.io

